# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3889935f137d8b040deadfa17b194cdde1fe7d118610d791130316a3197e170e385dfc2dfd04440abb8baed6d8846ff7a26f6e557ca6c5500fbe17ddcea9506e

test:
  secret_key_base: 5b308f972fc8c23c05b26009f1492f6b43223c82a07ce3d6c1d0fbf3827359d689252e1018b558fb7d74975c745e0cc364ea8469b30a6d87996f27f852c3676e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
